### PR TITLE
dsl support for stringjoin struct repr and stringprefix union repr

### PR DESCRIPTION
**Pull request by ericevenchick**
Adds support for `representation stringjoin` for structs and `representation stringprefix` for unions.

### CODE REVIEW

**Comment by rvagg** [comment]
Nice work @ericevenchick! would you mind taking a look at how the tests for these are working and see if you can figure out how to pull those in? They should be using fixtures that are coming in from the ipld/ipld repo, but those fixtures may need to be touched up to make them work (the fixtures are based on some older code but things have changed a bit since them, including the way we consume them).

**Comment by ericevenchick** [comment]
Hey @rvagg! I actually do have those test fixtures working and just pushed to https://github.com/ericevenchick/ipld. Since it's a submodule, I'm not sure of the best way to go about the PR process.

Should I go ahead and create a PR on the ipld repo, get that merged, then update the submodule on this PR?

**Comment by warpfork** [comment]
I went ahead and reviewed and merged that fixture PR -- you're unstuck now :)  (I do admit, the process of PR'ing something with a submodule bump when you can't push to the existing URL is pretty gnarly, and I hadn't given that a lot of thought before...)

Pretty sure the rest of this LGTM too after the bump to include the new test fixtures.

**Comment by warpfork** [comment]
Huzzah, new tests, and green!  I think I can merge this then.

Thank you!!  It's wonderful to have help making this more system complete!

**Pull request merged**
