### PR TITLE
schema/gen/go: batch file writes via a bytes.Buffer

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Comment by mvdan** [comment]
There are better libraries that perform better at atomic file replaces, like google/renameio, but I feel like that's a bit overkill for a code generator right now - especially given the added dependency.

**Comment by mvdan** [comment]
Uh, weird that the tests broke. Looking.

**Comment by mvdan** [comment]
Ah, the tests run in parallel, so no buffer reuse. Should be green now.

**Comment by warpfork** [comment]
Okay, phew, that was the one thing I was going to comment made me uncomfortable anyway :sweat_smile: (admittedly, unexported, so maybe could've been fine, but, still.)

**Pull request merged**
