### PR TITLE
a couple of panic fixes

### PR DESCRIPTION
**Pull request by mvdan**
(see commit messages - please do not squash)

Updates #342.

### CODE REVIEW

**Review by rvagg — APPROVED** [review]
very nice, more to test and do here but the builders and assemblers look fixed and tested and those are my top-line concerns since they are a vector for panic via codecs; the rest seem more likely to arise from programmer errors I think so the prioritisation here seems right. 👌

**Comment by mvdan** [comment]
Thanks for the review! And yup, that's how I prioritized.

**Comment by mehdi2021mp** [comment]
Bacap via wallet

**Comment by mehdi2021mp** [comment]
F

**Pull request merged**
