### PR TITLE
fix(codecs): error when encoding maps whose lengths don't match entry count

### PR DESCRIPTION
**Pull request by rvagg**
Further to #332 I figured it'd be good to insert this sanity check so we can't produce this kind of malformed data at the codec level. I was wondering how I might add a test for this since it requires a dodgy type, but it turns out bindnode fails with AbsentOptionals when this is added, so that at least tells me this is correct.

Do you think this warrants adding a test? I think it would mean writing a full, dodgy, map type that reports the wrong `Length()`.

### CODE REVIEW

**Review by mvdan — COMMENTED** [review]
We could write a unit test, but I also think it's not super important given how a bindnode schema test is already failing on this :) The logic also seems pretty straightforward.

I'll push the bindnode fix on this branch, too, so we can merge with green checks.

**Comment by mvdan** [comment]
I pushed the bindnode fix to this branch, PTAL :) cc @warpfork 

Also, your codec changes LGTM!

**Comment by rvagg** [comment]
Additions lgtm

**Review by mvdan — APPROVED** [review]
Let's merge then; this is definitely a good change :) I have more bindnode fixes coming, so a merge will help with conflicts. @warpfork let me know if any of this doesn't look right and we can do a follow-up PR.

**Pull request merged**
